-- What is the total revenue generated by each customers.
		SELECT 
			c.customer_id , 
			c.first_name , 
			c.country,
			SUM(f.sales_amount) AS Total_revenue
		FROM gold.fact_sales f 
		LEFT JOIN gold.dim_customers c
		ON f.customer_key=c.customer_key 
		GROUP BY c.customer_id , c.first_name , c.country
		ORDER BY Total_revenue DESC

-- The 3  customers with fewest order placed (Using window Function ) ? 

	SELECT
			customer_id,
			first_name,
			last_name,
			Total_orders
	FROM 
		(SELECT
			c.customer_id,
			c.first_name,
			c.last_name,
			COUNT(DISTINCT order_number) AS Total_orders,
			ROW_NUMBER() OVER(ORDER BY COUNT(DISTINCT order_number)) AS p_rank
		FROM gold.fact_sales f
		LEFT JOIN gold.dim_customers c
		ON f.customer_key=c.customer_key
		GROUP BY c.customer_id,
				 c.first_name,
				 c.last_name) t 
	WHERE p_rank<=3

      
-- Analyze the sale sales over years
	
	SELECT 
		YEAR(Order_date) AS order_date,
		SUM(sales_amount) AS total_sales,
		COUNT(DISTINCT customer_key) AS total_customers,
		SUM(quantity) AS total_quantity
	FROM gold.fact_sales
	WHERE Order_date IS NOT NULL
	GROUP BY YEAR(Order_date)
	ORDER BY YEAR(Order_date)

-- Total sales per month and the running total of sales over time 
	
	SELECT 
	order_date,
	total_sales,
	SUM(total_sales) OVER(ORDER BY order_date) AS runnig_total
	FROM
		(SELECT 
			DATETRUNC(year,order_date) AS order_date,
			SUM(sales_amount) AS total_sales
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL 
		GROUP BY DATETRUNC(year,order_date) 
		) t

-- The yearly performance of products by comparing each product's sale to both its average sales performace 
-- and the previous year's sales.

	WITH yearly_product_sales AS
	(
		SELECT 
		YEAR(f.order_date) AS order_date,
		p.product_name,
		SUM(f.sales_amount) AS current_sales
		FROM gold.fact_sales f
		LEFT JOIN gold.dim_product p
		ON f.product_key=p.product_key
		WHERE f.Order_date IS NOT NULL 
		GROUP BY YEAR(order_date),p.product_name
	)

	SELECT 
		order_date,
		product_name,
		current_sales,
		AVG(current_sales) OVER(PARTITION BY product_name) avg_sales,
		current_sales-AVG(current_sales) OVER(PARTITION BY product_name) comp,
		CASE WHEN current_sales-AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'Below Average'
			 WHEN current_sales-AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'Above Average'
			 ELSE 'Average'
		END AS avg_change,
		LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_date) py_sales,
		current_sales-LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_date) py,
		CASE WHEN current_sales-LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_date) < 0 THEN 'Decreasing'
			 WHEN current_sales-LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_date) > 0 THEN 'Increasing'
			 ELSE 'Equal'
		END AS py_change
	FROM yearly_product_sales
	ORDER BY product_name,order_date

-- Which category contribute the most to the overall sales ?

	SELECT 
	category,
	Total_sales,
	CONCAT(ROUND((CAST(Total_sales AS FLOAT)/SUM(total_sales) OVER())*100,2),'%') AS percentage_
	FROM
	(
		SELECT 
			p.category AS category,
			SUM(s.sales_amount) AS Total_sales
		FROM Gold.fact_sales s
		LEFT JOIN gold.dim_product p
		ON s.product_key=p.product_key
		GROUP BY p.category
	) t
	ORDER BY total_sales DESC

-- Segment products into ranges and count how many products fall into each segment 
	
	WITH product_seg AS (
	SELECT 
	product_key,
	product_name,
	product_cost,
	CASE WHEN product_cost < 100 THEN 'Below 100' 
		 WHEN product_cost BETWEEN 100 AND 500  THEN '100-500'
		 WHEN product_cost BETWEEN 500 AND 1000 THEN '500-1000'
		 ELSE 'Above 1000'

	END Cost_range
	FROM gold.dim_product)

	SELECT 
	 cost_range,
	 COUNT(product_key) AS total_products
	 FROM product_seg
	 GROUP BY cost_range
	 ORDER BY total_products DESC

-- Group customers into three segmentats based upon their spending behaviour : 
	-- VIP : Customers with atleast 12 months of history and spending more than RS.5000
	-- Regular : Customers with atleast 12 months of history but spending RS.5000 or less
	-- New : Customers with a lifespan less than 12 months.
-- And find the total number of customers by each group
	WITH cust_spending AS 
	(
	SELECT 
	c.customer_key,
	SUM(f.sales_amount) AS total_spending,
	MIN(f.order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(MONTH,MIN(f.order_date),MAX(order_date)) AS lifespan
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON f.customer_key=c.customer_key
	GROUP BY c.customer_key
	)

	SELECT
	customer_segment,
	COUNT(customer_key) AS total_customers
	FROM
	(
	SELECT 
	customer_key,
	total_spending,
	lifespan,
	CASE WHEN lifespan>=12 AND total_spending > 5000 THEN 'VIP'
		 WHEN lifespan>=12 AND total_spending <= 5000 THEN 'Regular'
		 ELSE 'New'
	END customer_segment
	FROM cust_spending
	)T
	GROUP BY customer_segment
	ORDER BY COUNT(customer_key) DESC








